playlist/blueprints/channel/__init__.py
from playlist.blueprints.channel.views import channel

playlist/blueprints/channel/views.py
from flask import Blueprint, render_template

from playlist.source import get_sources

channel = Blueprint('channel', __name__, template_folder='templates')


@channel.route('/channel')
def index():
    return render_template('channel/index.html', sources=get_sources(True))


@channel.route('/channel/search')
def search():
    return render_template('channel/search.html', sources=get_sources(True))

playlist/blueprints/channel/templates/channel/index.html
{% extends 'layouts/base.html' %}

{% block title %}Playlist - channels{% endblock %}

{% block scripts %}
<script defer src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
<script defer src="{{ url_for('static', filename='js/channel.js') }}"></script>
<script>
  const data = {{ sources | tojson | safe }};
</script>
{% endblock %}

{% block body %}
<div class="container-centered">
  <div id="vm">
    <section class="page-header">
      <h1>Channels</h1>
      <a href="{{ url_for('channel.search') }}" class="btn-frontal" title="Add new channel">+</a>
    </section>
    <source-select :sources="sources" @change="setSource"></source-select>
    <channels :source="source"></channels>
  </div>
</div>
{% endblock %}

playlist/blueprints/channel/templates/channel/search.html
{% extends 'layouts/base.html' %}

{% block title %}Playlist - channel search{% endblock %}

{% block scripts %}
<script defer src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
<script defer src="{{ url_for('static', filename='js/channel-search.js') }}"></script>
<script>
  const data = {{ sources | tojson | safe }};
</script>
{% endblock %}

{% block body %}
<div class="container-centered">
  <div id="vm">
    <section class="page-header">
      <h1>Channel search</h1>
    </section>
    <channel-search-form :sources="sources" @search="setSearchData"></channel-search-form>
    <channel-search-list :request="request"></channel-search-list>
  </div>
</div>
{% endblock %}