playlist/__init__.py
__version__ = '0.1.0'

playlist/api/__init__.py
from flask import Blueprint


api = Blueprint('api', __name__)

from . import channel

playlist/app.py
from flask import Flask

from playlist.api import api
from playlist.blueprints.main import main
from playlist.blueprints.channel import channel

from playlist.db import db


def create_app(config_name):
    app = Flask(__name__)

    config_module = f'playlist.config.{config_name.capitalize()}Config'

    app.config.from_object(config_module)

    app.register_blueprint(main)
    app.register_blueprint(channel)
    app.register_blueprint(api, url_prefix='/api_v1')

    init_extensions(app)

    return app


def init_extensions(app):
    db.init_app(app)

playlist/blueprints/channel/__init__.py
from playlist.blueprints.channel.views import channel

playlist/blueprints/channel/views.py
from flask import Blueprint, render_template

from playlist.source import get_sources

channel = Blueprint('channel', __name__, template_folder='templates')


@channel.route('/channel')
def index():
    return render_template('channel/index.html', sources=get_sources(True))


@channel.route('/channel/search')
def search():
    return render_template('channel/search.html', sources=get_sources(True))

playlist/blueprints/main/__init__.py
from playlist.blueprints.main.views import main

playlist/blueprints/main/views.py
from flask import Blueprint, render_template

main = Blueprint('main', __name__)


@main.route('/')
def home():
    return render_template('home.html')

playlist/db/__init__.py
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

playlist/source/__init__.py
from http import HTTPStatus
import mimetypes
import os
import requests

from playlist.db.channel import Channel

sources = {
    'youtube': {
        'name': 'Youtube',
    },
}
RESULTS_PER_PAGE = 25


def get_sources(select=False):
    result = sources

    if select:
        result = [{'slug': key, 'name': value['name']} for key, value in sources.items()]

    return result


def process_external_data(data, status_code, response_processor, error_processor, **kwargs):
    if status_code >= HTTPStatus.BAD_REQUEST:
        proc = error_processor(data)
    else:
        proc = response_processor(data, status_code, **kwargs)

    return proc.process()


def save_thumbnails(subject):
    thumbnails_path = os.path.join(os.getenv('BASE_DIR'), 'playlist', 'static', 'thumb')
    thumbnails = {key: value for key, value in subject.items() if key.startswith('thumbnail')}
    subject_id = subject.get('id')

    for key, url in thumbnails.items():
        response = requests.get(url)

        size = key.split('_')[1]
        content_type = response.headers['content-type']
        extension = mimetypes.guess_extension(content_type)
        thumbnail_name = os.path.join(thumbnails_path, f'{subject_id}_{size}{extension}')

        with open(thumbnail_name, "wb") as f:
            f.write(response.content)

playlist/templates/home.html
{% extends 'layouts/base.html' %}

{% block title %}Playlist{% endblock %}

{% block body %}
<div></div>
{% endblock %}

playlist/templates/layouts/base.html
{% from "macros.html" import nav_link with context %}

<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <title>{% block title %}{% endblock %}</title>
  <meta name="description" content="{% block meta_description %}{% endblock %}">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
  {% block scripts %}{%endblock%}
</head>

<body>
  <div class="page-container">
    <header class="header">
      <a href="{{ url_for('main.home') }}">
        <svg viewBox="0 0 128 128" class="logo">
          <use href="#logo-playlist"></use>
        </svg><h1 class="site-name">Playlist</h1>
      </a>
    </header>
    <aside class="sidenav">
      <ul>
        {{ nav_link('channel.index', 'Channels', '0 0 100 100') }}
      </ul>
    </aside>
    <main class="main">
      {% block body %}{% endblock %}
    </main>
    <footer class="footer"></footer>
  </div>

  <svg width="0" height="0" display="none" xmlns="http://www.w3.org/2000/svg">
    <symbol id="icon-channels" viewBox="128 0 128 128">
      <path d="m158.5 44.65 15.8 9.124m-19.56-23.13c4.903 2.831 6.583 9.1 3.752 14-2.831 4.903-9.1 6.583-14 3.752s-6.583-9.1-3.752-14c2.831-4.903 9.1-6.583 14-3.752m3.752 52.71 15.8-9.124m-29.81 5.372c4.903-2.831 11.17-1.151 14 3.752 2.831 4.903 1.151 11.17-3.752 14-4.903 2.831-11.17 1.151-14-3.752-2.831-4.903-1.151-11.17 3.752-14m47.52 23.1-8e-5 -18.25m-10.25 28.5c0-5.662 4.59-10.25 10.25-10.25 5.662 0 10.25 4.59 10.25 10.25 0 5.662-4.59 10.25-10.25 10.25-5.662 0-10.25-4.59-10.25-10.25m43.77-29.6-15.8-9.124m19.56 23.13c-4.903-2.831-6.583-9.1-3.752-14 2.831-4.903 9.1-6.583 14-3.752 4.903 2.831 6.583 9.1 3.752 14-2.831 4.903-9.1 6.583-14 3.752m-3.752-52.71-15.8 9.124m29.81-5.372c-4.903 2.831-11.17 1.151-14-3.752-2.831-4.903-1.151-11.17 3.752-14 4.903-2.831 11.17-1.151 14 3.752 2.831 4.903 1.151 11.17-3.752 14m-47.52-23.1v18.25m10.25-28.5c0 5.662-4.59 10.25-10.25 10.25-5.662 0-10.25-4.59-10.25-10.25 0-5.662 4.59-10.25 10.25-10.25 5.662 0 10.25 4.59 10.25 10.25m10.25 48.96a20.5 20.5 0 0 1-20.5 20.5 20.5 20.5 0 0 1-20.5-20.5 20.5 20.5 0 0 1 20.5-20.5 20.5 20.5 0 0 1 20.5 20.5z" />
    </symbol>
    <symbol id="icon-search" viewBox="256 0 128 128">
      <path d="m328.4 71.94 49.42 49.42m-38.29-76.34a38.11 38.11 0 0 1-38.11 38.11 38.11 38.11 0 0 1-38.11-38.11 38.11 38.11 0 0 1 38.11-38.11 38.11 38.11 0 0 1 38.11 38.11z" />
    </symbol>
    <symbol id="logo-playlist" viewBox="0 0 128 128">
      <path id="channels" d="m59.17 110.4 2.801-19.33m-9.071 24.01c0.4382-3.025 3.246-5.121 6.27-4.683 3.025 0.4383 5.121 3.246 4.683 6.27s-3.246 5.121-6.27 4.683c-3.025-0.4383-5.121-3.246-4.683-6.27m57.04-46.33-14.47-2.317m19.06 8.657c-3.018-0.4834-5.072-3.322-4.589-6.339 0.4834-3.018 3.322-5.072 6.339-4.589 3.018 0.4834 5.072 3.322 4.589 6.339-0.4834 3.018-3.322 5.072-6.34 4.589m-18.26 25.56-11.94-15.46m10.94 23.22c-1.868-2.419-1.422-5.894 0.9969-7.762 2.419-1.868 5.894-1.422 7.762 0.9968 1.868 2.419 1.422 5.894-0.9968 7.762-2.419 1.868-5.894 1.422-7.762-0.9968m10.15-76.32-15.58 11.78m23.33-10.71c-2.437 1.844-5.908 1.363-7.752-1.075-1.844-2.437-1.363-5.908 1.075-7.752 2.437-1.844 5.908-1.363 7.752 1.075 1.844 2.437 1.363 5.908-1.075 7.752m-75.36 55.54 6.915-6.563m-14.74 6.359c2.217-2.104 5.72-2.012 7.823 0.2045 2.104 2.217 2.013 5.719-0.2043 7.823-2.217 2.104-5.719 2.012-7.823-0.2045-2.104-2.217-2.013-5.719 0.2043-7.823m-0.2958-57.75c-1.885-0.06877-3.675 0.8271-4.749 2.377-1.742 2.51-1.12 5.957 1.389 7.7 2.512 1.741 5.959 1.116 7.7-1.396 1.742-2.51 1.12-5.957-1.389-7.7-0.8696-0.6022-1.894-0.9426-2.951-0.9808zm4.34 8.681 7.839 5.436zm-16.01 32 19.15-3.848m-25.67-0.4872c2.996-0.6021 5.914 1.339 6.516 4.335 0.6021 2.996-1.339 5.914-4.335 6.516-2.996 0.6021-5.914-1.339-6.516-4.335s1.339-5.914 4.335-6.516m52.17-49.55 0.839 14.63m4.369-20.47c0.175 3.051-2.157 5.667-5.208 5.842-3.051 0.175-5.667-2.157-5.842-5.208-0.175-3.051 2.157-5.667 5.208-5.842 3.051-0.175 5.667 2.157 5.842 5.208m26.84 50.59c-0.3021 16.3-13.76 29.26-30.06 28.96-16.3-0.302-29.26-13.76-28.96-30.06 0.3021-16.3 13.76-29.26 30.06-28.96 16.3 0.302 29.26 13.76 28.96 30.06" />
      <path id="wave" d="m37.02 62.35h4.253c2.674 0 3.295-2.621 4.433-5.627 0.6771-1.788 1.569-1.61 2.121-0.2067 0.5697 1.448 0.9387 4.882 1.217 6.159 0.6706 3.074 1.744 3.614 2.397 0.4075 1.051-5.166 1.799-8.665 2.392-10.55 0.5922-1.89 2.321-1.736 2.898-0.1366 0.5765 1.6 1.736 10 2.984 16.87 1.818 10.01 3.33 10.16 4.513 4.362 1.183-5.795 2.391-21.65 3.286-25.3 0.6345-2.591 2.161-2.472 3.032 0.6481 0.8704 3.121 2.486 16.25 3.16 19.51 0.6739 3.26 2.503 3.395 3.182-2.753 0.3076-2.79 0.4406-8.117 0.9261-10.25 0.31-1.36 1.465-0.9611 1.835 0.2116 0.7681 2.431 1.229 7.704 2.232 10.8 0.8551 2.642 2.024 3.64 2.797 0.2476 0.6588-2.888 2.273-4.409 4.198-4.393 1.925 0.01544 6.853 0 6.853 0" />
    </symbol>
  </svg>
</body>

</html>

playlist/templates/macros.html
{% macro nav_link(endpoint, name, view_box) %}
{% if request.endpoint.endswith(endpoint) %}
  <li class="active">
    <a class="menu-item" href="{{ url_for(endpoint) }}" title="{{ name }}">
      <svg viewBox="{{ view_box }}" class="icon">
        <use href="#icon-{{ name | lower }}"></use>
      </svg>
    </a>
  </li>
{% else %}
  <li>
    <a class="menu-item" href="{{ url_for(endpoint) }}" title="{{ name }}">
      <svg viewBox="{{ view_box }}" class="icon">
        <use href="#icon-{{ name | lower }}"></use>
      </svg>
    </a>
  </li>
{% endif %}
{% endmacro %}